### ISSUE TITLE
Send the drivers required

### ISSUE THREAD

**Issue by Eeman1113** [ashklempton/plant-monitoring#1]
Drivers bro drivers!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by ashkln** [comment]
If you have the arduino with you run this
pip install serial flask gunicorn Flask-cors

**Comment by AbhisekGanguly** [comment]
closing this issue as the problem is solved.
